package controller;

public enum TypeDePerception {
	Perception_de_soi_meme,
	Perception_supposee_que_le_sexe_oppose_a_de_soi,
	Recherche_personnelle_dans_le_sexe_oppose,
	Recherche_generale_dans_le_sexe_oppose,
	Recherche_supposee_du_sexe_oppose
}
